let musicDB = [
    {
        id: 0,
        name: "Pathetique",
        author_name: "Beethoven",
        img: "adult1.jpg",
        type: "adult",
        musicName: "adult1.mp3",
    },
    {
        id: 1,
        name: "4 Ballades",
        author_name: "Chopin",
        img: "adult2.jpg",
        type:"adult",
        musicName: "adult2.mp3",
    },
    {
        id: 2,
        name: "Prelides",
        author_name: "Debussy",
        img: "adult3.jpg",
        type: "adult",
        musicName: "adult3.mp3",
    },
    // {
    //     id: 3,
    //     name: "Lakme",
    //     author_name: "Delibes",
    //     img: "adult4.jpg",
    //     type: "adult",
    //     musicName: "adult4.mp3",
    // },
    {
        id: 4,
        name: "Salut d_amour",
        author_name: "Elgar",
        img: "adult5.jpg",
        type: "adult",
        musicName: "adult5.mp3",
    },
    {
        id: 5,
        name: "Nap",
        author_name: "Monoman",
        img: "adult6.jpg",
        type: "adult",
        musicName: "adult6.mp3",
    },
    {
        id: 6,
        name: "Home",
        author_name: "Rui Fujishiro",
        img: "adult7.jpg",
        type: "adult",
        musicName: "adult7.mp3",
    },
    {
        id: 7,
        name: "le lac de Come",
        author_name: "Galos",
        img: "teenager1.jpg",
        type: "teenager",
        musicName: "teenager1.mp3",
    },
    {
        id: 8,
        name: "Peer Gynt",
        author_name: "Greig",
        img: "teenager2.jpg",
        type:"teenager",
        musicName: "teenager2.mp3",
    },
    {
        id: 9,
        name: "Liebestraume",
        author_name: "Liszt",
        img: "teenager3.jpg",
        type:"teenager",
        musicName: "teenager3.mp3",
    },
    // {
    //     id: 10,
    //     name: "Schubert",
    //     author_name: "Ave Maria",
    //     img: "teenager4.jpg",
    //     type: "teenager",
    //     musicName: "teenager4.mp3",
    // },
    {
        id: 11,
        name: "Gianni Schicchi",
        author_name: "Giacomo Puccini",
        img: "teenager5.jpg",
        type: "teenager",
        musicName: "teenager5.mp3",
    },
    {
        id: 12,
        name: "Meditation",
        author_name: "Monoman",
        img: "teenager6.jpg",
        type: "teenager",
        musicName: "teenager6.mp3",
    },
    {
        id: 13,
        name: "Piano Sonata 11",
        author_name: "Mozart",
        img: "children1.jpg",
        type: "children",
        musicName: "children1.mp3",
    },
    {
        id: 14,
        name: "Piano Sonata 18",
        author_name: "Mozart",
        img: "children2.jpg",
        type:"children",
        musicName: "children2.mp3",
    },
    {
        id: 15,
        name: "Lieder Ohne",
        author_name: "Mendelssohn",
        img: "children3.jpg",
        type:"children",
        musicName: "children3.mp3",
    },
    {
        id: 16,
        name: "The Carnival of the Animals",
        author_name: "Saint Saens",
        img: "children4.jpg",
        type: "children",
        musicName: "children4.mp3",
    },
    {
        id: 17,
        name: "Sunshine",
        author_name: "Various artists",
        img: "children5.jpg",
        type: "children",
        musicName: "children5.mp3",
    },
    {
        id: 18,
        name: "Flower Nap",
        author_name: "Monoman",
        img: "children6.jpg",
        type: "children",
        musicName: "children6.mp3",
    },
    {
        id: 19,
        name: "Missing U",
        author_name: "Monoman",
        img: "children7.jpg",
        type: "children",
        musicName: "children7.mp3",
    },
];

export default musicDB;
